"""add TA fields to payslip

Revision ID: 835a7875c33b
Revises: 1f515b1f4483
Create Date: 2025-11-07 00:30:01.436509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '835a7875c33b'
down_revision: Union[str, Sequence[str], None] = '1f515b1f4483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payslip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regular_hours', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('overtime_hours', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('late_deductions', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payslip', schema=None) as batch_op:
        batch_op.drop_column('late_deductions')
        batch_op.drop_column('overtime_hours')
        batch_op.drop_column('regular_hours')

    # ### end Alembic commands ###
