"""added payroll and payslip tables

Revision ID: aee4f0a775ef
Revises: 78fbde24d801
Create Date: 2025-11-06 05:10:42.860840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aee4f0a775ef'
down_revision: Union[str, Sequence[str], None] = '78fbde24d801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pay_period_start', sa.Date(), nullable=False),
    sa.Column('pay_period_end', sa.Date(), nullable=False),
    sa.Column('pay_date', sa.Date(), nullable=False),
    sa.Column('total_gross_pay', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_deductions', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_net_pay', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payslip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('payroll_run_id', sa.Integer(), nullable=False),
    sa.Column('gross_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sss_deduction', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('philhealth_deduction', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pagibig_deduction', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('withholding_tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('other_deductions', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_deductions', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_pay', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payslip')
    op.drop_table('payroll_run')
    # ### end Alembic commands ###
