"""added employee table

Revision ID: b515ad7ae10b
Revises: 942b0c7436ba
Create Date: 2025-11-06 03:55:06.856679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b515ad7ae10b'
down_revision: Union[str, Sequence[str], None] = '942b0c7436ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('employee_id_number', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('position', sa.String(length=64), nullable=True),
    sa.Column('date_hired', sa.Date(), nullable=True),
    sa.Column('salary_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('tin', sa.String(length=15), nullable=True),
    sa.Column('sss_num', sa.String(length=15), nullable=True),
    sa.Column('philhealth_num', sa.String(length=15), nullable=True),
    sa.Column('pagibig_num', sa.String(length=15), nullable=True),
    sa.Column('bank_account_num', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_employee_id_number'), ['employee_id_number'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_employee_id_number'))

    op.drop_table('employee')
    # ### end Alembic commands ###
