"""add leave balance table

Revision ID: d15c3574ed4d
Revises: fad6a8dc247e
Create Date: 2025-11-07 00:56:24.188199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd15c3574ed4d'
down_revision: Union[str, Sequence[str], None] = 'fad6a8dc247e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.String(length=50), nullable=False),
    sa.Column('entitlement', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('used', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'leave_type', name='_employee_leave_type_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leave_balance')
    # ### end Alembic commands ###
