"""Added holiday table

Revision ID: d3be4261d73d
Revises: 4e428229f20f
Create Date: 2025-11-30 02:55:24.309416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3be4261d73d'
down_revision: Union[str, Sequence[str], None] = '4e428229f20f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holiday',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payroll_run', schema=None) as batch_op:
        batch_op.alter_column('pay_period_start',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('pay_period_end',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('pay_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_run', schema=None) as batch_op:
        batch_op.alter_column('pay_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('pay_period_end',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('pay_period_start',
               existing_type=sa.DATE(),
               nullable=False)

    op.drop_table('holiday')
    # ### end Alembic commands ###
